language: java
sudo: false
script: mvn clean verify
deploy:
  provider: azure_web_apps
  verbose: true
  on:
    all_branches: true
  before_deploy: "git add target/ROOT.war; git commit -m 'dummy'"
