language: java
sudo: false

script: mvn clean verify

#Azure WebApps git repo deployment
after_success:
- mkdir -p webapps/ROOT
- cp target/ROOT.war webapps/ROOT.war
- git config user.email "pabarham@microsoft.com"
- git config user.name "Paul T. Barham"
- git add webapps/ROOT.war webapps/ROOT
- git commit -m "commit ROOT.war"
- git remote add azure https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@$AZURE_WA_SITE.scm.azurewebsites.net:443/$AZURE_WA_SITE.git
- git push --force azure HEAD:master

# deploy:
  # provider: azure_web_apps
  # verbose: true
  # skip_cleanup: true
  # on:
    # all_branches: true
  # file: /home/travis/build/paultbarham/deep-space/target/ROOT.war
  
