language: java
sudo: false

script: mvn clean verify

before_deploy: "git config --global user.email 'pabarham@microsoft.com'"
before_deploy: "git config --global user.name 'Paul T. Barham'"
before_deploy: "git commit -am 'dummy'"

deploy:
  provider: azure_web_apps
  verbose: true
  # skip_cleanup: true
  on:
    all_branches: true
  
