language: java
sudo: false

script: mvn clean verify

before_deploy: "git commit -am 'dummy'"

deploy:
  provider: azure_web_apps
  verbose: true
  # skip_cleanup: true
  on:
    all_branches: true
  
